services:
  telegram-payment-bot:
    build: .
    container_name: telegram_payment_bot_container
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-conf/config.ini}
      - TZ=Europe/Rome
    restart: unless-stopped
    stop_grace_period: 10s

    deploy:
      resources:
        limits:
          memory: 512M

    volumes:
      - ./app/conf:/code/conf:ro
      - ./app/lang:/code/lang:ro
      - ./app/cred:/code/app/cred
      - ./app/session:/code/session
      - ./app/logs:/code/logs

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
